### ISSUE TITLE
Allow user to set the progress of slider

### ISSUE THREAD

**Issue by patrickelectric** [j2only/vue-slide-unlock#37]
Programatically we want to simulate the slide-unlock event from a physical joystick, right now it's not possible to access the percentage from our part, only internally using a mouse or a touchscreen.

**Comment by j2only** [comment]
@patrickelectric Please, check 0.5.4 version. I've added a new prop "position" where you can pass the progress percentage (from 0 to 100) of the slider.

**Comment by j2only** [comment]
> it appears that completed it not being emitted once position gets to 100%, is that expected ?

No, completion should be emitted as soon as the position reaches 100%. Check it out in demo https://j2only.github.io/vue-slide-unlock.

**Comment by JoaoMario109** [comment]
Here's a revised version of your issue comment, with grammar and formatting improvements:

---

I've noticed that the `@completed` event does not seem to be emitted when `emulateSlideFromProps` is utilized. I think that the following modification could address this issue.

https://github.com/j2only/vue-slide-unlock/blob/b22c518eeea0d9feaf8894112ff4cbffc9eb324a/lib/SlideUnlock.vue#L228

Maybe change to the following

```javascript
if (computedPosition >= sliderWidth.value - props.height) {
    complete();
    passVerify();
}
```

**Comment by j2only** [comment]
@JoaoMario109 Thank you for your pull request. I added changes to version 0.5.5.
